### PR TITLE
Use updated Divvy endpoint

### PR DESCRIPTION
**Pull request by shirgoldbird**
The Divvy endpoint referenced in the code no longer works and returns incorrect data. Updating to this one makes it work again!

### CODE REVIEW

**Comment by iandees** [comment]
Thanks!

**Comment by ShevaDas** [comment]
@iandees Thanks a ton for the quick merge! Any chance you can update your Heroku app as well? :) Great simple API, btw, exactly what I need.

**Comment by iandees** [comment]
Sure thing! I'm glad there are people using it still.

**Comment by iandees** [comment]
@ShevaDas The public API is updated.

**Pull request merged**
